### ISSUE TITLE
After last update all timers stop to works in blish hud

### ISSUE THREAD

**Issue by malagus** [Dev-Zhao/Timers_BlishHUD#18]
After last update blish hud can't load any timer 
![timers](https://user-images.githubusercontent.com/12558492/213943498-40a26774-0fa2-46d3-8ee8-7dbb1fd4322a.png)

**Comment by malagus** [comment]
Blish hud failed update to 1.0 and this module don't work at older versions

**Comment by Dev-Zhao** [comment]
@malagus Try downloading the latest BlishHud 1.0 version to https://new.blishhud.com/

Some people have reported that upgrading to this new version using the chest while Blish is open can cause this issue.
